try {
    let a = 25;
    console.log(a);
    throw "Run the programe and get your answer"

} catch (err) {
    console.log(err)

} finally {
    console.log("Hello World")
}